// src/employeeData.js
const employees = [
    {
      rank: 1,
      name: "Rakesh Sharma",
      designation: "UI/UX Designer",
      hoursWorked: "7(42)",
      changes: "1.5 hrs",
      isIncrease: true,
      workingDuration: 42,
    },
    {
      rank: 2,
      name: "Ankita Thakur",
      designation: "HR Recruiter",
      hoursWorked: "7(41)",
      changes: "1.5 hrs",
      isIncrease: false,
      workingDuration: 41,
    },
    {
      rank: 3,
      name: "Sarah Yadav",
      designation: "Product Manager",
      hoursWorked: "7(40)",
      changes: "1.5 hrs",
      isIncrease: true,
      workingDuration: 40,
    },
    {
      rank: 4,
      name: "Harsha Shivhare",
      designation: "Designer",
      hoursWorked: "7(37)",
      changes: "1.5 hrs",
      isIncrease: true,
      workingDuration: 37,
    },
    {
      rank: 5,
      name: "Vanhi Rai",
      designation: "Video Editor",
      hoursWorked: "7(37)",
      changes: "1.5 hrs",
      isIncrease: false,
      workingDuration: 37,
    },
    {
      rank: 6,
      name: "Bhanu Sharma",
      designation: "Business Analyst",
      hoursWorked: "7(32)",
      changes: "1.5 hrs",
      isIncrease: false,
      workingDuration: 32,
    },
    {
      rank: 7,
      name: "Sunil Yadav",
      designation: "Developer",
      hoursWorked: "7(24)",
      changes: "1.5 hrs",
      isIncrease: true,
      workingDuration: 24,
    },
    {
      rank: 8,
      name: "Akash Roy",
      designation: "Business Analyst",
      hoursWorked: "7(21)",
      changes: "1.5 hrs",
      isIncrease: false,
      workingDuration: 21,
    },
    {
      rank: 9,
      name: "Rohit Soni",
      designation: "Developer",
      hoursWorked: "7(20)",
      changes: "1.5 hrs",
      isIncrease: false,
      workingDuration: 20,
    },
    {
      rank: 10,
      name: "Suraj Chauhan",
      designation: "Developer",
      hoursWorked: "7(18)",
      changes: "1.5 hrs",
      isIncrease: false,
      workingDuration: 18,
    },
  ];
  
  export default employees;